//
// Generated file, do not edit! Created by opp_msgtool 6.0 from group.msg.
//

#ifndef __GROUP_M_H
#define __GROUP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class values;
class sensors_trust;
class request;
class offer;
class sp_to_sc;
class req_to_sp;
class ser_to_sc;
class fb_to_cloud;
/**
 * Class generated from <tt>group.msg:1</tt> by opp_msgtool.
 * <pre>
 * message values
 * {
 *     int label;
 *     string id;
 *     simtime_t time;
 *     int batterie;
 *     int byteLength;
 * }
 * </pre>
 */
class values : public ::omnetpp::cMessage
{
  protected:
    int label = 0;
    omnetpp::opp_string id;
    omnetpp::simtime_t time = SIMTIME_ZERO;
    int batterie = 0;
    int byteLength = 0;

  private:
    void copy(const values& other);

  protected:
    bool operator==(const values&) = delete;

  public:
    values(const char *name=nullptr, short kind=0);
    values(const values& other);
    virtual ~values();
    values& operator=(const values& other);
    virtual values *dup() const override {return new values(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getLabel() const;
    virtual void setLabel(int label);

    virtual const char * getId() const;
    virtual void setId(const char * id);

    virtual omnetpp::simtime_t getTime() const;
    virtual void setTime(omnetpp::simtime_t time);

    virtual int getBatterie() const;
    virtual void setBatterie(int batterie);

    virtual int getByteLength() const;
    virtual void setByteLength(int byteLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const values& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, values& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>group.msg:9</tt> by opp_msgtool.
 * <pre>
 * message sensors_trust
 * {
 *     string node;
 *     double tr;
 * }
 * </pre>
 */
class sensors_trust : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string node;
    double tr = 0;

  private:
    void copy(const sensors_trust& other);

  protected:
    bool operator==(const sensors_trust&) = delete;

  public:
    sensors_trust(const char *name=nullptr, short kind=0);
    sensors_trust(const sensors_trust& other);
    virtual ~sensors_trust();
    sensors_trust& operator=(const sensors_trust& other);
    virtual sensors_trust *dup() const override {return new sensors_trust(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getNode() const;
    virtual void setNode(const char * node);

    virtual double getTr() const;
    virtual void setTr(double tr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const sensors_trust& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, sensors_trust& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>group.msg:14</tt> by opp_msgtool.
 * <pre>
 * message request
 * {
 *     string node;
 *     double need;
 * }
 * </pre>
 */
class request : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string node;
    double need = 0;

  private:
    void copy(const request& other);

  protected:
    bool operator==(const request&) = delete;

  public:
    request(const char *name=nullptr, short kind=0);
    request(const request& other);
    virtual ~request();
    request& operator=(const request& other);
    virtual request *dup() const override {return new request(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getNode() const;
    virtual void setNode(const char * node);

    virtual double getNeed() const;
    virtual void setNeed(double need);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const request& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, request& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>group.msg:19</tt> by opp_msgtool.
 * <pre>
 * message offer
 * {
 *     string node;
 *     double offre;
 * }
 * </pre>
 */
class offer : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string node;
    double offre = 0;

  private:
    void copy(const offer& other);

  protected:
    bool operator==(const offer&) = delete;

  public:
    offer(const char *name=nullptr, short kind=0);
    offer(const offer& other);
    virtual ~offer();
    offer& operator=(const offer& other);
    virtual offer *dup() const override {return new offer(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getNode() const;
    virtual void setNode(const char * node);

    virtual double getOffre() const;
    virtual void setOffre(double offre);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const offer& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, offer& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>group.msg:26</tt> by opp_msgtool.
 * <pre>
 * message sp_to_sc
 * {
 *     string sc;
 *     string sp;
 *     double need;
 *     double service;
 * }
 * </pre>
 */
class sp_to_sc : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string sc;
    omnetpp::opp_string sp;
    double need = 0;
    double service = 0;

  private:
    void copy(const sp_to_sc& other);

  protected:
    bool operator==(const sp_to_sc&) = delete;

  public:
    sp_to_sc(const char *name=nullptr, short kind=0);
    sp_to_sc(const sp_to_sc& other);
    virtual ~sp_to_sc();
    sp_to_sc& operator=(const sp_to_sc& other);
    virtual sp_to_sc *dup() const override {return new sp_to_sc(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSc() const;
    virtual void setSc(const char * sc);

    virtual const char * getSp() const;
    virtual void setSp(const char * sp);

    virtual double getNeed() const;
    virtual void setNeed(double need);

    virtual double getService() const;
    virtual void setService(double service);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const sp_to_sc& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, sp_to_sc& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>group.msg:33</tt> by opp_msgtool.
 * <pre>
 * message req_to_sp
 * {
 *     string sp;
 *     string sc;
 *     double need;
 *     double service;
 * }
 * </pre>
 */
class req_to_sp : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string sp;
    omnetpp::opp_string sc;
    double need = 0;
    double service = 0;

  private:
    void copy(const req_to_sp& other);

  protected:
    bool operator==(const req_to_sp&) = delete;

  public:
    req_to_sp(const char *name=nullptr, short kind=0);
    req_to_sp(const req_to_sp& other);
    virtual ~req_to_sp();
    req_to_sp& operator=(const req_to_sp& other);
    virtual req_to_sp *dup() const override {return new req_to_sp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSp() const;
    virtual void setSp(const char * sp);

    virtual const char * getSc() const;
    virtual void setSc(const char * sc);

    virtual double getNeed() const;
    virtual void setNeed(double need);

    virtual double getService() const;
    virtual void setService(double service);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const req_to_sp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, req_to_sp& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>group.msg:40</tt> by opp_msgtool.
 * <pre>
 * message ser_to_sc
 * {
 *     string sc;
 *     string sp;
 *     double need;
 *     double service;
 * }
 * </pre>
 */
class ser_to_sc : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string sc;
    omnetpp::opp_string sp;
    double need = 0;
    double service = 0;

  private:
    void copy(const ser_to_sc& other);

  protected:
    bool operator==(const ser_to_sc&) = delete;

  public:
    ser_to_sc(const char *name=nullptr, short kind=0);
    ser_to_sc(const ser_to_sc& other);
    virtual ~ser_to_sc();
    ser_to_sc& operator=(const ser_to_sc& other);
    virtual ser_to_sc *dup() const override {return new ser_to_sc(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSc() const;
    virtual void setSc(const char * sc);

    virtual const char * getSp() const;
    virtual void setSp(const char * sp);

    virtual double getNeed() const;
    virtual void setNeed(double need);

    virtual double getService() const;
    virtual void setService(double service);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ser_to_sc& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ser_to_sc& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>group.msg:47</tt> by opp_msgtool.
 * <pre>
 * message fb_to_cloud
 * {
 *     string sp;
 *     string sc;
 *     double fb;
 * }
 * </pre>
 */
class fb_to_cloud : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string sp;
    omnetpp::opp_string sc;
    double fb = 0;

  private:
    void copy(const fb_to_cloud& other);

  protected:
    bool operator==(const fb_to_cloud&) = delete;

  public:
    fb_to_cloud(const char *name=nullptr, short kind=0);
    fb_to_cloud(const fb_to_cloud& other);
    virtual ~fb_to_cloud();
    fb_to_cloud& operator=(const fb_to_cloud& other);
    virtual fb_to_cloud *dup() const override {return new fb_to_cloud(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSp() const;
    virtual void setSp(const char * sp);

    virtual const char * getSc() const;
    virtual void setSc(const char * sc);

    virtual double getFb() const;
    virtual void setFb(double fb);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const fb_to_cloud& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, fb_to_cloud& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline values *fromAnyPtr(any_ptr ptr) { return check_and_cast<values*>(ptr.get<cObject>()); }
template<> inline sensors_trust *fromAnyPtr(any_ptr ptr) { return check_and_cast<sensors_trust*>(ptr.get<cObject>()); }
template<> inline request *fromAnyPtr(any_ptr ptr) { return check_and_cast<request*>(ptr.get<cObject>()); }
template<> inline offer *fromAnyPtr(any_ptr ptr) { return check_and_cast<offer*>(ptr.get<cObject>()); }
template<> inline sp_to_sc *fromAnyPtr(any_ptr ptr) { return check_and_cast<sp_to_sc*>(ptr.get<cObject>()); }
template<> inline req_to_sp *fromAnyPtr(any_ptr ptr) { return check_and_cast<req_to_sp*>(ptr.get<cObject>()); }
template<> inline ser_to_sc *fromAnyPtr(any_ptr ptr) { return check_and_cast<ser_to_sc*>(ptr.get<cObject>()); }
template<> inline fb_to_cloud *fromAnyPtr(any_ptr ptr) { return check_and_cast<fb_to_cloud*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __GROUP_M_H

